import GoogleOneTapLogin from "@/components/GoogleOneTapLogin";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Signin/Login",
  description: "Generated by Next.js",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
      <GoogleOneTapLogin />
    </html>
  );
}
