import GoogleOneTapLogin from "@/components/GoogleOneTapLogin";

export const metadata = {
  title: "Signin/Login",
  description: "Generated by Next.js",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>{children}</body>
      <GoogleOneTapLogin />
    </html>
  );
}
